# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5328e5364881f8b20e02e4fb080809d4894981bf1a00e4d4c3c1fdda18dfcfbe5a9e3fb98b98c5251bd1f6bef3f3cdb1f543e22188bfe72925f335f24978b088

test:
  secret_key_base: 7df627a67321af08f6fe721201693d76b62bfea2277e65fb51036fe5efa177c3795a0425589d267d639bc5c73a70592eba099622d29b19f169a9e752a56e48ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
